### ISSUE TITLE
detailPageSlug not accessible in custom partial/snippet

### ISSUE THREAD

**Issue by riartem** [jan-vince/smallrecords#1]
Thank you for great plugin.
It's very usefull, but not usable "out of the box" in cases when we need to call **Record** component without adding it to page through `{% component 'records' %}`.
I try to render list manually, but discover that `detailPageSlug` is not accessible in that context.
I fixed this with adding few lines of code (if it possible, add it to plugin):
```php
// file Records.php line 15 (after)
public $detailPageSlug;

// line 111 (after onRender method)
public function onRun()
{
    $this->detailPageSlug = $this->property('detailPageSlug');
}
```

It will do that code fully working:
```twig
{% for record in records.items %}
      <a href="/{{ records.detailPageSlug }}/{{ record.slug }}">
         {{ record.name }}
      </a>
{% endfor %}
```

**Comment by jan-vince** [comment]
Hi and thanks for the PR!

I will test it and merge.

**Comment by jan-vince** [comment]
Once again thanks pro PR, but this will works for all properties:

````
{{records.property('detailPageSlug')}}
{{records.property('areaSlug')}}
...
````
