### ISSUE TITLE
October CMS 3

### ISSUE THREAD

**Issue by afdstudio** [jan-vince/smallrecords#100]
Hi! Tried to install it on OctoberCMS V3.
But when I try to create a record inside a list I get this error:
Missing configuration for view.form in RelationController definition area
~/modules/backend/behaviors/RelationController.php line 881

Any thoughts on how to fix this?
Is this plugin compatible with V3?

Thank you in advance!

**Comment by jan-vince** [comment]
No, it works on OC1.

Try Tailor in OC3 as it is much better alternative.

**Comment by afdstudio** [comment]
Hi @jan-vince ! Thank you a lot for the reply. Trying Tailor for the first time and it looks really nice!
