### ISSUE TITLE
Error on Areas

### ISSUE THREAD

**Issue by xJoeyv** [jan-vince/smallrecords#11]
I had a error when visiting Areas after I created 1 Area ( "Portfolio" ).

```
We're sorry, but an unhandled error occurred. Please see the details below.

count(): Parameter must be an array or an object that implements Countable
D:\xampp\htdocs\xjoeyv\plugins\janvince\smallrecords\Plugin.php line 193
```
( Error Page (if you save the html and open it: https://gist.github.com/xJoeyv/0868e444c9e3ecfc60d0abe9b006a736 )

Creating and updating one by changing the route works still fine!

**Comment by jan-vince** [comment]
It is fixed in new version.

Thanks for issue!
