### ISSUE TITLE
404 when record is not found

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallrecords#14]
Shouldn't the 404 response look sth like this?

file: components/RecordDetails.php

```
    public function onRun()
    {

        $this->recordDetail = $this->page['recordDetail'] = $this->getRecord();

        if( $this->property('recordSlug') and !$this->recordDetail ){
            **return \Response::make($this->controller->run('404'), 404);**
        }

    }
```
Maybe it should check if page 404 exist first... if not then do abort(404...?

Regard,
Darjan

**Comment by jan-vince** [comment]
Hi @zlobec,

have you tried this? Edited as you propose you will get 404 headers inlined in default October error page.

I believe that this is too late to return response like this in [execution cycle](https://octobercms.com/docs/plugin/components#page-cycle-handlers).

When /404 or /error page do not exists in template, OC default will be show.

What do you think?

**Comment by zlobec** [comment]
Hi,

sorry for late response. I really don't have that much experience to know for sure. The modificaiton does work, when there is a /404 page. But if there is none, it does not.

Regard,
Darjan

**Comment by jan-vince** [comment]
Hi @zlobec 

I have tested this and it works even when there is no /404 or /error page.

If both are missing, default October error page is shown.

And HTTP 404 - Not found header is correctly send.

I will close this but feel free to open this issue if you experience any problem!
