### ISSUE TITLE
Categories component feature request

### ISSUE THREAD

**Issue by leonaze** [jan-vince/smallrecords#20]
Hello,
Is it possible that the component Categories "Only with records in list" use record "categories" field to filter active categories ?
Thanks.

**Comment by jan-vince** [comment]
Hi @leonaze , what is your use case for this?

**Comment by jan-vince** [comment]
Categories component works only with main categories (the one selected on Info tab in Category select box).

![snimek obrazovky 2018-05-08 v 17 18 57](https://user-images.githubusercontent.com/1104383/39766183-f61141dc-52e3-11e8-8d08-da346db98a8c.png)


But you need to work with multi-categories on Categories tab, right?

I have added new option **Use multi-categories** to version 1.11.0.

![snimek obrazovky 2018-05-08 v 18 22 32](https://user-images.githubusercontent.com/1104383/39769740-5217da14-52ed-11e8-8e68-97d5c069e32d.png)

When checked, categories from Categories tab are used so you can decide whether single-category or multi-categories are used.

*I only wish to have more time to make a better documentation :)*

**Comment by leonaze** [comment]
Hi @jan-vince ,
Really nice ! I will try next week because I am on vacation but great plugin and awesome support.
Thanks.

**Comment by jan-vince** [comment]
You are welcome!
