### ISSUE TITLE
Component Categories only active records

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallrecords#21]
@jan-vince would it be possible for the Categories component to have the option to not show categories that do not have a single active record. At the same time to only count the number of active records not all records as is now (it counts also inactive records).

Regard,
Darjan

**Comment by jan-vince** [comment]
Hi @zlobec, this should be possible from version 2.1.2.

I was trying to create a simple UI for this but I am still not very happy with that.

The main idea behind this is:

* There are new properties in Categories component for filtering records by list and active state
* There is also an option to filter returned categories list to only those with filtered records (you can filter records but keep all categories; or the other way out)

Default Categories component partial has an example code so if you want to test it (or look at code), give it a try :)

**Comment by zlobec** [comment]
@jan-vince I'll give it a spin and let you know! Thanks!
