### ISSUE TITLE
Records and Categories don't work with translated slugs

### ISSUE THREAD

**Issue by raelcv** [jan-vince/smallrecords#22]
"Record not found!"
I thing this is a very useful plugin and I just want to relate an issue that I did not find a solution.

**Comment by jan-vince** [comment]
Hi @raelcv , I will look at this as soon as I have some free time!

Thanks for the issue.

**Comment by zlobec** [comment]
Need this too :D

**Comment by jan-vince** [comment]
Finally added translatable slugs for RecordDetail and CategoryDetail slugs.

Thanks @kosmonowt for pushing me to finish this!
