### ISSUE TITLE
Suggestion: Attachments and external URLs

### ISSUE THREAD

**Issue by Verbat** [jan-vince/smallrecords#23]
Hello,

I was wondering if it's possible to add another possibility to the attachment section.
Sometimes i also would like to add additional files which are not hosted on our server as the original file is kept more up to date from the creator. The location and name stays the same but the files are updated frequently.

Basically i would like to use an external URL like http://example.com/downloads/file.pdf or a combination of both lokal and several external files referenced with an URL like above to add them in the attachment section.

Is this possible or is there another good way of doing this?

Another good option would be to include the media finder to select already uploaded files like it is used at the Image section.

Thanks

**Comment by jan-vince** [comment]
Hi @Verbat I will add this to my todo list!

Thanks for issue.

**Comment by zlobec** [comment]
@Verbat You could create and add an attribute "External URL" that can get attached to a record.

**Comment by jan-vince** [comment]
Hi @Verbat , the solution from @zlobec is probably the right one.

Or from version 2.0 you can create your own custom form (Custom repeater) where you can store text or a file from Media.
