### ISSUE TITLE
Records not filtered by category

### ISSUE THREAD

**Issue by jonnydevv** [jan-vince/smallrecords#25]
I've been trying really hard to filter records by category without success.

```
title = "Historial de Projetos"
url = "/historial-de-projetos"

[records]
areaSlug = "projetos-de-investimento"
categorySlug = "{{ :category }}"
tagSlug = "{{ :tag }}"
activeOnly = 0
limit = 10
detailPageSlug = "projetos"
detailPageParam = "slug"
orderBy = "date"
orderByDirection = "DESC"

```
When I access  _historial-de-projetos_ page it shows the the records.

```
title = "Historial de Projetos por Categorias"
url = "/historial-de-projetos/:category"

[records]
areaSlug = "projetos-de-investimento"
categorySlug = "{{ :category }}"
tagSlug = "{{ :tag }}"
activeOnly = 0
limit = 10
detailPageSlug = "projetos"
detailPageParam = "slug"
orderBy = "date"
orderByDirection = "DESC"
```

When I access  _historial-de-projetos/restaurantes_ page it shows no records at all.

I'm generating the categories menu with component categories:

```
[categories projetCategories]
areaSlug = "0"
categorySlug = "{{ :category }}"
activeOnly = 1
rootOnly = 0
limit = 10
```

Any ideas what might be wrong?

<img width="720" alt="screen shot 2018-07-18 at 17 44 55" src="https://user-images.githubusercontent.com/2188826/42898369-78289c96-8ab2-11e8-9520-d9b5a56194e8.png">
<img width="783" alt="screen shot 2018-07-18 at 17 44 20" src="https://user-images.githubusercontent.com/2188826/42898382-82a3d56e-8ab2-11e8-8f08-f7d3c8494115.png">

**Comment by jan-vince** [comment]
HI @jonnydevv,

I think that `areaSlug` in `[categories projetCategories]` block should be "projetos-de-investimento":

```
[categories projetCategories]    
areaSlug = "projetos-de-investimento"    
categorySlug = "{{ :category }}"    
activeOnly = 1    
rootOnly = 0    
limit = 10    
```

**Comment by jonnydevv** [comment]
Found the problem. In the list, I add selected categories field for multi categories per record instead of category field. But projects can only be filtered when only have one category. If we select multi categories, those records are not showed.
<img width="643" alt="screen shot 2018-07-19 at 15 18 16" src="https://user-images.githubusercontent.com/2188826/42952241-913b88fa-8b67-11e8-8376-d109eeebd28b.png">
<img width="647" alt="screen shot 2018-07-19 at 15 18 09" src="https://user-images.githubusercontent.com/2188826/42952249-96f9fe70-8b67-11e8-957f-bf42ac5c376b.png">

**Comment by jan-vince** [comment]
Hi @jonnydevv,

I have added property `useMultiCategories` to Records component.

When used than records will be filtered based on `Categories` selected on Categories tab.

When not used than Records are filtered by main `Category` set on Info tab.

Thanks for the issue!

**Comment by jonnydevv** [comment]
Great, thank you very much!
