### ISSUE TITLE
Order by name only sorts default language

### ISSUE THREAD

**Issue by jonnydevv** [jan-vince/smallrecords#26]
Hello,
I've noticed that component records when set ```orderBy = "name"``` will only sort by default language.
Here's an example where my default language is Portuguese:

```
[records entradas]
areaSlug = "entradas"
categorySlug = "{{ :category }}"
tagSlug = "{{ :tag }}"
activeOnly = 1
limit = 10
detailPageSlug = "homepage"
detailPageParam = "{{ :slug }}"
orderBy = "name"
orderByDirection = "ASC"
```

<img width="694" alt="screen shot 2018-07-21 at 14 11 09" src="https://user-images.githubusercontent.com/2188826/43036381-662153c2-8cf0-11e8-8cb2-cb955f61c9c9.png">
<img width="696" alt="screen shot 2018-07-21 at 14 11 21" src="https://user-images.githubusercontent.com/2188826/43036382-664deff4-8cf0-11e8-8f11-5c2dbd66144d.png">

As you can see, it is sort in Portuguese only even when I change current language.
Am i missing something?

Thanks in advance.

**Comment by jan-vince** [comment]
Hi @jonnydevv 

I have never used Small Records to sort items by selected language so I will test this and try to fix it!

**Comment by jan-vince** [comment]
Hi @jonnydevv, can you please try using `Order as Collection` option in new SmallRecords version?

This should do the trick.

![snimek obrazovky 2018-11-16 v 10 08 56](https://user-images.githubusercontent.com/1104383/48611952-c46af200-e987-11e8-83e4-e39e3839484c.png)
