### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by pAndyVl** [jan-vince/smallrecords#28]
Tell me how to do pagination

**Comment by jan-vince** [comment]
Hi @pAndyVl, right now only by extending my plugin.

I will add this to my todo list and try to add pagination soon.

Thanks for issue!

**Comment by jan-vince** [comment]
Hi @pAndyVl , I have added pagination to version 2.1.

*You have to allow `Limit number or records` in Records component.*

There is a paginator used in default Records component if you need.

**Comment by pAndyVl** [comment]
Thanks for the work. How to stylize paginator output? {{records.items.render | raw}} prints the standard layout

**Comment by jan-vince** [comment]
Hi @pAndyVl if you need a custom layout (the default is based on Bootstrap), you will need to create your own code based on [Pagination](https://octobercms.com/docs/services/pagination).
