### ISSUE TITLE
SiteSearch compatibility

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallrecords#29]
This would be a great feature: https://octobercms.com/plugin/offline-sitesearch

Regard,
Darjan

**Comment by jan-vince** [comment]
@zlobec added to my todo list, thanks!

**Comment by dlr1251** [comment]
Hi Jan, great plugin! I have to work on a project with this feature. 
I am building a somehow large catalogue of products. The idea would be to have a search field in the frontend with filtering for the categories, tags and lists (just like the backend but in the frontend aswell) and a simple pagination.
Me and a colleague would like to contribute to your plugin by extending its functionalities. Is there any way to help you in some way to make this happen? Best regards

**Comment by jan-vince** [comment]
Hi @dlr1251,

just create PR and I will be happy to include it to the plugin.

**Comment by Hessel91** [comment]
I tried Custom Google Search Plugin, however, the records are on a secured page (user plugin) and I can't find the files. Do you have a simple work around for a search field that can find the created records?

**Comment by jan-vince** [comment]
Hi @Hessel91,

the best would be to make a custom search provider for Offline Site Search.

I have this on my todo list but I have no spare time to create it :(

**Comment by sagjatome** [comment]
> Hi @Hessel91,
> 
> the best would be to make a custom search provider for Offline Site Search.
> 
> I have this on my todo list but I have no spare time to create it :(

Still no time?

**Comment by jan-vince** [comment]
Hi @Hessel91, I am going to end support of Small Records so I will not add this feature.

I do not use Small Records for more than a year and switched to Taylor in OC3 that is much more powerfull and easier to use.

Sorry I do not have good news.


Best regards,

Jan
