### ISSUE TITLE
Can I make use of 2 or more recordDetail component in a single page?

### ISSUE THREAD

**Issue by onemedicare** [jan-vince/smallrecords#3]
Can I make use of 2 or more recordDetail component in a single page?

I have tried alias but it seems that the aliasing the components doesn't work

**Comment by jan-vince** [comment]
Hi, I have never used it this way.

Will look at it and let you know - this should work (and I will fix it if not right now :)

Thanks for an issue!

Jan

**Comment by onemedicare** [comment]
I did notice that changing the default.htm with __SELF__ variable does the trick. Hope this help. Thanks for a simple yet very very useful plugin.
`<div class="record-box {{ cssClass }}">

    {% if __SELF__.recordDetail.preview_image %}
        <img alt="{{ __SELF__.recordDetail.name }}" src="{{ __SELF__.recordDetail.preview_image.getPath }}" />
    {% endif %}

    <h3>
        {{ __SELF__.recordDetail.name }}
    </h3>

</div>`

**Comment by jan-vince** [comment]
Hi @onemedicare this is fixed in v 1.1.10 - as I don't use component's default partials much (even those made by myself :), I haven't noticed this.

Thank you for posting this issue!

Jan
