### ISSUE TITLE
Best way to put record name in page meta title

### ISSUE THREAD

**Issue by leonaze** [jan-vince/smallrecords#30]
Hi,
I am searching to put the record name in the meta title of the page... If someone can help me.
Thanks.

**Comment by zlobec** [comment]
I do it sth like this. You put this in the code part of the page:

```
function onEnd() {
  $this->page->meta_title = $this->recordDetail->getAttributeValueBySlug('meta-title');
}
```
I have a seperate attribute called meta-title to give a special name to the record. Just type recordDetail->name instead to get the record name.

**Comment by leonaze** [comment]
@zlobec Thank you. It works perfectly.
