### ISSUE TITLE
Sorting relations?

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallrecords#32]
Is there a way to sort the record relations to any other value than added ascending order?

For example I would like to sort tags by slug not by the added order, so I can group them together by similarity and make them easier to find...

... or have the option to filter tags?

Regard,
Darjan

**Comment by jan-vince** [comment]
Hi @zlobec,

if you mean sorting Tags related to record, you can use [Collection methods](
https://octobercms.com/docs/services/collections#method-sortby) like:

`{{ recordDetail.tags.sortBy('name') }}`

Component for separate Tags listing is not in production version yet.

**Comment by zlobec** [comment]
@jan-vince No. I meant in the backend, when adding tags to record. The sort is by default ID, I guess...

**Comment by jan-vince** [comment]
Hi @zlobec , Tags are now ordered by name in Record's form.

Thanks for issue!
