### ISSUE TITLE
can't get the right slug from single record

### ISSUE THREAD

**Issue by Hessel91** [jan-vince/smallrecords#33]
Hi Jan, thank you for this plugin!
Unfortunately, I can't get it working properly. 
What are the correct settings for the records page and the connection to the single record page?
The slug keeps returning the wrong url > /default
Is there a demo backend available, cause there is not much documentation.
Please let me know.

**Comment by ezersky** [comment]
+1

**Comment by jan-vince** [comment]
Hi @Hessel91, the simplest scenario:

Records page with [records] component:
```
[records]
areaSlug = "my-area"
detailPageSlug = "record-detail"
detailPageParam = "slug"
```

Detail page (file name record-detail.htm) with [recordDetail] component and URL: /record-detail/:slug
```
[recordDetail]
recordSlug = "{{ :slug }}"
areaSlug = "my-area"
```

PS: I know about missing documentation but had no time to add it. This plugin was meant just for my projects :)

But I will add more details about using this plugin as more people asking for help.
