### ISSUE TITLE
Correct code path for all images from recordDetail.images 

### ISSUE THREAD

**Issue by Hessel91** [jan-vince/smallrecords#34]
Hi, I was able to get the stored images from recordDetail.images, however I cant figure out how to show them correctly. (see added screenshot) Could you perhaps take a look?

I have uploaded multiple images, and I would like to show them all, but currently the are all displayed like this: <img src="%20img1uploadpath%20img2uploadpath2 etc

here is what my component looks like:
    `{% if recordDetail.images %}
    <img alt="" src="{{ recordDetail.images }}" />
    {% endif %}
    <h3 class="record-box-title">
      {{ __SELF__.recordDetail.name }}
      </h3>
`

![schermopname 10](https://user-images.githubusercontent.com/7326568/45184909-ad41b280-b228-11e8-9735-aa001e6bbc83.png)

**Comment by jan-vince** [comment]
Hi @Hessel91, recordDetail.image returns Collection of uploaded images so you have to iterate through it like:

```
{% for image in redordDetail.images %}

<img src="{{ image.getThumb(300,300) }}">

{% endfor %}
```

Or you can use `image.getPath` if you want to get original file.
