### ISSUE TITLE
Accessing nested content for template

### ISSUE THREAD

**Issue by surtin** [jan-vince/smallrecords#36]
Trying to place testimonials and what not on a page for record details.

`{% for testimonial in records.items.testimonials %}`
`     {% if testimonial is not empty %}`
`          {{ testimonial.testimonial_content }}`
`      {% endif %}`
` {% endfor %}`

That code doesn't seem to access anything but an empty array.

What's the best way to call these nested objects for templates (testimonials and content blocks)?

**Comment by jan-vince** [comment]
Hi @surtin, I can't test it right now, but you have to iterate over items.

```
{% for record in records.items %}

  {% for testimonial in record.testimonials %}
     {{ testimonial.testimonial_content }}
  {% endfor %}

{% endfor %}
```

**Comment by jan-vince** [comment]
Hi @surtin if you still have a problem with accessing data try to update to 2.0 version.

I have rewritten default components partials with examples how to access all of Small Records data.
