### ISSUE TITLE
correct path for atribute and tag

### ISSUE THREAD

**Issue by Hessel91** [jan-vince/smallrecords#37]
Hi I'm sorry for asking but can you tell me what is the correct path for "tag"  and "attribute"?

for Tag i tried:      `{{  __SELF__.recordDetail.tag }}` to show the active tags that are selected
however that didn't worked so far. 

And I created an attribute called "Plaats" translated: "place" which I tried to output like this:
      `{% for attribute in record.attributes %}`
      `{{ attribute.plaats }} : {{ attribute.value }}`
      `{% endfor %}`
but thats not working either. 

Can you please show me what the correct path is so I can use your plugin for more future projects?

**Comment by AlexZuu** [comment]
> Hi I'm sorry for asking but can you tell me what is the correct path for "tag" and "attribute"?
> 
> for Tag i tried: `{{ __SELF__.recordDetail.tag }}` to show the active tags that are selected
> however that didn't worked so far.
> 
> And I created an attribute called "Plaats" translated: "place" which I tried to output like this:
> `{% for attribute in record.attributes %}`
> `{{ attribute.plaats }} : {{ attribute.value }}`
> `{% endfor %}`
> but thats not working either.
> 
> Can you please show me what the correct path is so I can use your plugin for more future projects?



    {% for attribute in **recordDetail.attributes** %}

    {{ attribute.name }} : {{ attribute.value }}

    {% endfor %}

**Comment by Hessel91** [comment]
Thanks! And the correct path for tag?

**Comment by jan-vince** [comment]
Hi @Hessel91 , for Tag the very same code:

```
{% for tag in recordDetail.tags %}

{{ tag.name }}

{% endfor %}
```
