### ISSUE TITLE
Replace record preview_image form widget to mediafinder

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallrecords#4]
Hi,

I've tried to replace the record preview_image "fileupload" widget to "mediafinder". When creating/editing a recod, the widget does load, but it does not store the selected file. 

So far i changed the models/record/fields.yaml file. What else do I need to change to make this work? I am quite new to Laravel and OctoberCMS.

I would like the mediafinder because a lot of records will have duplicate images not unique images. Same will have to be applied to Images tab too.

Regard,
Darjan

**Comment by jan-vince** [comment]
Hi,

you would need an extra DB table column to store media file path.

But don't waste your time I have added this to 1.5 version as this is quite useful for anyone :)

You can allow Media preview in List config.

Thanks for an issue!

Best regards,

Jan

![small-records-media](https://user-images.githubusercontent.com/1104383/34246421-d255e602-e62e-11e7-90e5-5180eb07464f.png)
