### ISSUE TITLE
Custom form fields

### ISSUE THREAD

**Issue by daniel-somersault** [jan-vince/smallrecords#44]
Hi there
I am creating a portfolio record page and I'm having problems retrieving the custom field values using Twig. A couple of the field names I have created so far are; clientBackground (text) , projectSummary (richtext) and clientImage (mediafinder).  They aren't being used as repeatable fields but will add add a few more in in due course.

I am quite new to October, apologies if this is something simple, so any help would be appreciated.

Thanks

**Comment by jan-vince** [comment]
Hi @daniel-somersault,

best place to look is in plugin's components directory. There is complete example of retrieving data.

For record detail look in `/plugins/janvince/smallrecords/components/recorddetail/default.htm`.

Sorry for late answer.
