### ISSUE TITLE
Not all data being retrieved in front-end

### ISSUE THREAD

**Issue by thistehneisen** [jan-vince/smallrecords#45]
<img width="1680" alt="Screenshot 2019-03-29 at 12 44 19" src="https://user-images.githubusercontent.com/6432992/55229331-5e3f8700-5225-11e9-96d6-0b7711363201.png">
<img width="1680" alt="Screenshot 2019-03-29 at 12 44 52" src="https://user-images.githubusercontent.com/6432992/55229332-5e3f8700-5225-11e9-985d-e9f101bb9606.png">
<img width="1680" alt="Screenshot 2019-03-29 at 12 45 39" src="https://user-images.githubusercontent.com/6432992/55229333-5e3f8700-5225-11e9-94b9-e9d3472956fe.png">

As seen in the screenshots, there is preview image uploaded, and also an image in the Images tab. Neither of both are being outputted. Also, categories from Categories tab aren't being outputted.

How can this information be retrieved?

**Comment by kgangadhar** [comment]
category data can be retrieved using  
{% for cat in categories.items %}
{{cat.slug}}
{cat.name}}
{% endfor %} = > for all categories that you have created 

 if you want to retrieve the category of the current record use below code 
 {% for record in records.items %}
{{record.category.slug}}
{{record.category.name}}
 {% endfor %}

**Comment by jan-vince** [comment]
Hi @thistehneisen, have solved your problem?

@kgangadhar, thanks for support!
