### ISSUE TITLE
 Custom form fields overwrite record values

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallrecords#48]
@jan-vince I'm experiencing that Custom form fields with the same name as the record values are overwriten.

For example if in the Custom form field I set a field name as "name" it overwrites the record name value when saving values.

**Comment by jan-vince** [comment]
Hi @zlobec, I can't replicate this.

Is this still happening?

**Comment by zlobec** [comment]
@jan-vince  I'll plan to check this on the weekend and let you know about the issue.

**Comment by zlobec** [comment]
@jan-vince Hmm.. I can't replicate this again also. Closing the ticket.
