### ISSUE TITLE
Filtering custom attributes

### ISSUE THREAD

**Issue by hkan** [jan-vince/smallrecords#49]
Hi Jan! Thanks for this awesome plugin. It's been unbelievably helpful to build websites really quick.

One thing I'm currently having problem is that I cannot find a way to filter records by their attributes. Context: My client is a yacht buyer/seller firm and they list their current yachts. We want to build a search/filter system to filter yachts by their length and price.

I've looked through the files of the plugin and realized that in `components/Records.php` there isn't a method that it exposes the query object, but it creates a query and returns a collection directly. I'm happy to contribute via a PR but I'd like to get your opinion on how to accomplish it first.

**Comment by hkan** [comment]
Hey @jan-vince! Is it okay to assume that this repository is abandoned?

**Comment by jan-vince** [comment]
Hi @hkan,

I had not much time lately so i am sorry for the late answer.

If you want to work with Attributes you need such component (like Records, Tags, Categories).

There you can add methods to get records based on passed attributes.

If you create PR I will review it as soon as possible.
