### ISSUE TITLE
Testimonials do not work without Translate plugin

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallrecords#5]
Hi,

an error pops up when trying to insert record testimonials without the Translate plugin:
"The partial '_field_mltext.htm' is not found." 

Probably because the form widget for testimonal title, author and content is set "mltext" and "mlricheditor"?

Regard,
Darjan

**Comment by jan-vince** [comment]
Hi and thanks for this - it is a piece of my old config and as I always install Translate plugins I have never noticed this :(

It is fixed in 1.5.1 version!

Best regards,

Jan
