### ISSUE TITLE
How do I remove minimum 3 char from slug?

### ISSUE THREAD

**Issue by SalocinDotTEN** [jan-vince/smallrecords#51]
Record slugs cannot accept less than 3 characters. How do I get around this?

**Comment by zlobec** [comment]
Edit the "https://github.com/jan-vince/smallrecords/blob/59794c8b21d76b3941a57349cd7124a7dc0d61bf/models/Record.php#L46

**Comment by jan-vince** [comment]
Hi @SalocinDotTEN and @zlobec ,

this is probably not necessary so I have changed this to accept slugs from one letter (for all models).

Thanks for this and sorry for late answer!
