### ISSUE TITLE
Friendlier error message on same record slug / title.

### ISSUE THREAD

**Issue by SalocinDotTEN** [jan-vince/smallrecords#52]
First, thanks for bringing in my fixes. Much appreciated. I am using this plugin in a major website visited by tens of thousands now. Even used it to replace 301 Redirects plugin. Seems to be holding up very well.

My teammate (senior with 30 years experience) was using this and he was attempting to key in the same record name with the same slug.

An SQL error in a modal appeared, which I understood what it was. But to him, it seemed like the plugin had a really bad bug.

As I am intending to open the OctoberCMS backend to less technical team members for content management, is it possible to replace that with a friendlier error message such as "Record of the same name / slug exists"?

Thanks. Any tips/hacks will do as well.

**Comment by jan-vince** [comment]
Hi @SalocinDotTEN, I will add this to my todo list.

If you need it quickly, try to send a PR.

Sorry for late answer.
