### ISSUE TITLE
Custom url: How do I remove category & record from url?

### ISSUE THREAD

**Issue by Hessel91** [jan-vince/smallrecords#53]
Hi Jan, 

quick question:
How can I remove record & Category from the url.
so for example now it is:
mywebsite/category/test

& I would like: 
mywebsite/test'

same goes for record.

can you provide me the correct url set up in the page url and what to change in the component?

**Comment by kgangadhar** [comment]
you want to category slug and individual record slug from user url ... is it cirrect

**Comment by jan-vince** [comment]
Hi @Hessel91,

you can setup one page (can be a page with URL `/`) and add both Record detail and Category components.

Then set up both components to use same slug (eg `:slug`).

But my plugin do not test same slugs in records and categories so you can end up with situation when category and also record is found.
