### ISSUE TITLE
Default Category not returning any records

### ISSUE THREAD

**Issue by setianke** [jan-vince/smallrecords#57]
The default category storing all records like

`/category/default `

is not returning any records

**Comment by jan-vince** [comment]
Hi @setianke, there should be no category like this.

When `default` is used in a URL it means you haven't passed a slug.

Or please show your config.

**Comment by setianke** [comment]
Hi @jan-vince thank you for your reply, I assumed it was the default category due the component examples did have an "All" button which lead me to this category, therefore the CMS page with the corresponding components is the "All" page and making the page slug optional is the best solution. I am closing the issue as it is resolved in my opinion.
