### ISSUE TITLE
How show records on a blog-detail page?

### ISSUE THREAD

**Issue by exaline-ru** [jan-vince/smallrecords#58]
On setting:
![image](https://user-images.githubusercontent.com/46493161/67764069-223e0000-fa5a-11e9-88ba-400ad646ba1e.png)

And add some record to blog:
![image](https://user-images.githubusercontent.com/46493161/67764251-98426700-fa5a-11e9-8a49-68eb5c2f86a4.png)

How do I display them on a blog-detail page? (At least some instruction on that part)

**Comment by jan-vince** [comment]
Hi @exaline-ru, you can access records with `post.records`.

You can try Twig Dump plugin (from OctoberCMS marketplace) and than you can inspect all objects by `{{d(post)}}`.
