### ISSUE TITLE
Backend Errors

### ISSUE THREAD

**Issue by omfgtora** [jan-vince/smallrecords#6]
When in a list on the backend I have found a couple errors:

1) When you click "Create" and hit "Cancel", I get the following error:
`Missing argument 1 for JanVince\SmallRecords\Controllers\Records::index()
/var/www/html/plugins/janvince/smallrecords/controllers/Records.php line 49`

2) When in an item page within a list and you hit either of the arrows at the bottom right, I get the following error:
`Missing argument 2 for JanVince\SmallRecords\Controllers\Records::update()
/var/www/html/plugins/janvince/smallrecords/controllers/Records.php line 110`

**Comment by jan-vince** [comment]
Hi @omfgtora and thank you for the issue.

I have fixed first problem in version 1.6.1.

But I don't know what you mean by second one. Can you please add a screenshot of this?

**Comment by omfgtora** [comment]
Thank you so much for being so fast! And the keyboard shortcuts for the Save and NEW buttons is a brilliant idea, along with the auto focus.

For the 2nd error message, I get it when clicking one of the arrow buttons at the bottom right of a record that has already been created. Next to the delete button that looks like a trash can:
![image](https://user-images.githubusercontent.com/9193319/34901949-aa8c08fa-f7c6-11e7-8e86-76c7e319ecf0.png)

This is only visible when viewing existing records.

**Comment by jan-vince** [comment]
Hi @omfgtora,

I have forgot those arrows from my testing version of plugin. It was supposed to work only for records with DATE fields filled.

I was thinking about remove them but maybe they are useful to someone so I just added a test for all variables filled (so arraws will be visible ONLY when there are records with dates).

Please try version 1.6.2 and let me know.

PS: I have changed Create and NEW button position next to Create and close to keep order same as in other forms.
