### ISSUE TITLE
extending recordDetail

### ISSUE THREAD

**Issue by raskrial** [jan-vince/smallrecords#66]
Hi, 
if a drag n drop a single record component to my and add this line
{% component 'recordDetail' %}
everything work.
BUT ...
if i try to extend the component 'recordDetail' code to customise it, no data can be displayed ...

**Comment by jan-vince** [comment]
Hi @raskrial, what is code of your extended template?

**Comment by Mazikis** [comment]
Hi @jan-vince first of all awesome plugin but I am also facing this kind of issue for a single record.
When I leave {% component 'recordDetail' %} everything is fine but when I extend the component and for instance just try to add some class to existing markup ex.  <h3 **class="uk-article-title"** >< strong>{{ recordDetail.recordDetail.name }}</ strong></ h3> there is no data displayed. 

I hope there is way to fix this.

**Comment by jan-vince** [comment]
Hi,

I am not at my comp but i think you have a duplicate plugin name:

recordDetail.recordDetail.name

Try to use only

recordDetail.name


Best regards,

Jan



Odesláno z iPhonu

~~~~~~~~~~~~~~~~~~~~~
Ing. Jan Vince, Webdesigner
www.vince.cz


> 24. 7. 2020 v 13:07, Mazikis <notifications@github.com>:
> 
> recordDetail.recordDetail.name

**Comment by Mazikis** [comment]
Thank you @jan-vince I haven't even noticed that it was duplicated. :)
