### ISSUE TITLE
Non super admin cannot select date.

### ISSUE THREAD

**Issue by SalocinDotTEN** [jan-vince/smallrecords#67]
Hi.

I have a non admin that I have only allowed privileges to edit a record.

The date selector does not work but the time selector does.

When I try, there is the following error message in the console upon clicking the date field...

Uncaught TypeError: Cannot read property '0' of undefined
    at renderTitle (storm-min.js,qv=465.pagespeed.jm._-P1l4uWvk.js:407)
    at Pikaday.draw (storm-min.js,qv=465.pagespeed.jm._-P1l4uWvk.js:407)
    at Pikaday.show (storm-min.js,qv=465.pagespeed.jm._-P1l4uWvk.js:407)
    at HTMLInputElement.Pikaday.self._onInputFocus (storm-min.js,qv=465.pagespeed.jm._-P1l4uWvk.js:407)
renderTitle @ storm-min.js,qv=465.pagespeed.jm._-P1l4uWvk.js:407
draw @ storm-min.js,qv=465.pagespeed.jm._-P1l4uWvk.js:407
show @ storm-min.js,qv=465.pagespeed.jm._-P1l4uWvk.js:407
Pikaday.self._onInputFocus @ storm-min.js,qv=465.pagespeed.jm._-P1l4uWvk.js:407

I have also temporarily elevated the user to super admin but it still did not work.

However they work nicely when I login on my own.

**Comment by jan-vince** [comment]
Hi @SalocinDotTEN I don't think this is caused by plugin itself.

I have created new user with only privilege to access one list and no problem to edit any data.

**Comment by SalocinDotTEN** [comment]
Hi. 
Thanks for the response. Will investigate further.

**Comment by SalocinDotTEN** [comment]
Hi. Just to follow up. I have asked a similar question on stackoverflow and it turns out to be the language settings of the other administrator.

So thanks again for the response and assistance. :) 👍
