### ISSUE TITLE
How to implement search ?

### ISSUE THREAD

**Issue by Inklementia** [jan-vince/smallrecords#68]
great plugin but how to make records searchable?

**Comment by SalocinDotTEN** [comment]
I think basically you can code your own using the eloquent or database query that octobercms provides.

**Comment by jan-vince** [comment]
Hi @Inklementia,

for very simple search you can use Collection method `search()`. 

*I have in my todo to implement [SiteSearch](https://octobercms.com/plugin/offline-sitesearch).*

**Comment by Inklementia** [comment]
thanks! and yep, that would be awesome)
