### ISSUE TITLE
SQL Error on backend regarding "Active" state

### ISSUE THREAD

**Issue by omfgtora** [jan-vince/smallrecords#7]
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'visible' in 'where clause' (SQL: select count(*) as aggregate from `janvince_smallrecords_records` where visible <> true and `area_id` = 1)`

`/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php line 664`

By default the component setting is "only show active". I did not have this attribute selected on the list I had made. So instead of removing the default "only show active", I decided to simply add the attribute so I can disable items in the list.

However, when I added the new attribute I get the above error when trying to view the list from the backend when I was trying to add the active state to each of the records. This error shows on all lists I made, not just the one I tried to add the active attribute to.

**Comment by jan-vince** [comment]
Hi @omfgtora, this was a bug in my filter's code.

It is fixed in 1.6.3 version.

Thank you for issue!
