### ISSUE TITLE
Unexpected token "string" of value "records" ("end of print statement" expected).

### ISSUE THREAD

**Issue by febrianmosii** [jan-vince/smallrecords#70]
Hello, I just installed this plugin and I am about to use this with my project.

I followed the instruction of "Basic use case", and successfully called these components without any issue.

> {% component 'categories' %}

> {% component 'tags' %}

But when it comes to

> {% component 'records' %}

The error appeared

![image](https://user-images.githubusercontent.com/42708267/91586262-51c1df80-e97f-11ea-9190-822e3db25f55.png)

**My Page**

![image](https://user-images.githubusercontent.com/42708267/91586037-0d364400-e97f-11ea-9633-566f678eb4a3.png)

![image](https://user-images.githubusercontent.com/42708267/91586154-2b9c3f80-e97f-11ea-9f3c-644ef841cbb7.png)

**My records**

![image](https://user-images.githubusercontent.com/42708267/91586586-cd239100-e97f-11ea-8b69-c3f875bfcbce.png)

![image](https://user-images.githubusercontent.com/42708267/91586649-df053400-e97f-11ea-93f8-32b856250ff1.png)

Could you please help me to find what's wrong with my installation?

Thank you in advance

**Comment by jan-vince** [comment]
Hi @febrianmosii 

it looks like you have your own `default.htm` partial in `/themes/demo/partials/records` which overrides the default component template from Small Records.

Can you temporarily rename this folder to eg. `records2` so you can test the defaul plugin's compoment template?

**Comment by febrianmosii** [comment]
> Hi @febrianmosii
> 
> it looks like you have your own `default.htm` partial in `/themes/demo/partials/records` which overrides the default component template from Small Records.
> 
> Can you temporarily rename this folder to eg. `records2` so you can test the defaul plugin's compoment template?

Thank you!! :)
