### ISSUE TITLE
Category delete empty confirm message

### ISSUE THREAD

**Issue by xtsidx** [jan-vince/smallrecords#77]
Hi,
on update category page, click bottom-right  🗑(trash) icon.

Confirm message not found `janvince.smallrecords::lang.attributes.delete_confirm` 

![Снимок экрана от 2020-11-13 10-05-13](https://user-images.githubusercontent.com/1047595/99039100-c6c4ae80-2597-11eb-8ddc-81299cdcff6e.png)

**Comment by jan-vince** [comment]
Thanks, fixed in new version!

Best regards,

Jan
