### ISSUE TITLE
static_pages_hide_content prevents Snippets from appearing

### ISSUE THREAD

**Issue by Harti** [jan-vince/smallrecords#8]
**How to reproduce:**

* Enable Settings option "Static Pages > Hide Content Tab"
* Open a static page
* Click "Snippets", select any snippet

**Expected behavior:**
Snippet appears in the focused (or, if not applicable, the first) rich editor of the currently open tab at the caret position

**Actual behavior:**

* Snippet does not appear anywhere (probably goes to the "hidden" Content tab)
* Static page is marked as "having changes" (badge)

An alternative fix would be to make the option say "Caution, you will not be able to use Snippets" 😝

**Comment by jan-vince** [comment]
Hi @harti,

Snippets cannot be added anywhere else except main content richeditor.

This is bug in October and is already [issued](https://github.com/rainlab/pages-plugin/pull/238).

We have to wait to fix (or fix it ourselves :)

Thanks for issue!
