### ISSUE TITLE
Saving Records Closes the Record on Save

### ISSUE THREAD

**Issue by artistro08** [jan-vince/smallrecords#83]
When you create a new record and save it, it brings you back to the list screen. previous functionality was that it kept you on the record. Not sure what happened there. Video attached for reference. 

https://user-images.githubusercontent.com/6427230/103654380-6b75c380-4f2b-11eb-9c79-6ac71928bad1.mp4

**Comment by jan-vince** [comment]
Hi @artistro08,

to be true I don't know. As far as I remember this worked out of the box so there can be some October core update that prevent this to work any more.

I have overriden `create_onSave()` method and added redirects.

Try to update to 3.10.1. and let me know.

**Comment by artistro08** [comment]
Can confirm that fixed it. Sorry for the late reply. Much appreciated for the quick fix!
