### ISSUE TITLE
URL field to short

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallrecords#85]
Hi,

from client's feedback I've noticed that the URL field (191 chars) can be too short. I manually updated the field in my case to 2000+ chars. 

https://github.com/jan-vince/smallrecords/blob/d63ee3d1447c762e4708e533e58a180b5c72b971/updates/sr_tables.php#L25

Should this be changed to `$table->string('url', 2000)->nullable()->index();` to fit the max browser url length of IE?

Regard,
Darjan

**Comment by jan-vince** [comment]
Hi @zlobec I have changed columns size in version 1.51.3.

*But it looks like there is size limitation and columns's type is automatically changed from `VARCHAR` to `TEXT`. Which is OK for me :)*

**Comment by jan-vince** [comment]
Sorry - the version number for Small Records is 3.10.4.

I was able to change length to only 600 chars (due to index restrictions). 

I will inspect it further when I have a time.
