### ISSUE TITLE
please help to make categoryDetail component sortable descending

### ISSUE THREAD

**Issue by Hessel91** [jan-vince/smallrecords#86]
Hi, record details component is sortable by date, however, categoryDetails component is not. 
I copied the code and looked, changed again for hours but somehow I can't make it work.
Yes I know I'm not that good of a developer but I try my best. Can you please tell me how to make this component sort descending by date?

**Comment by jan-vince** [comment]
Hi @Hessel91,

`categoryDetail` component is meant to get **one category**. What exactly do you want to sort?

If you get category records from code like `{{ category.records }}` you should add `records` component along with `categoryDetail`. In `records` component you can define category slug and also sort order.

**Comment by Hessel91** [comment]
Thank you for your reply. 
your answer made me review my actions and I figured out that I had to check the records component checkbox for: "Filter by main category" on the category detail page for my issue to solve. thanks.
