### ISSUE TITLE
Error: To display list as a tree, the specified model must have a method "getChildren"

### ISSUE THREAD

**Issue by artistro08** [jan-vince/smallrecords#89]
Not sure how to handle this error, but I get this one when I navigate to a list. This happens with OctoberCMS v2.1. The records all display correctly, but I cannot access them

**Comment by jan-vince** [comment]
Hi @artistro08,

Small Records do not support OC2 yet. I plan to fix this when OC2 is production ready and I will need it for my projects.

**Comment by artistro08** [comment]
Awesome! It actually just hit stable a few days ago.

**Comment by artistro08** [comment]
Well, it appears it was an October Issue. Works fine now on October v2.1.3 but not October 2.1.0
