### ISSUE TITLE
Small issues and a suggestion

### ISSUE THREAD

**Issue by omfgtora** [jan-vince/smallrecords#9]
First, I really love your plugin and appreciate all the new features you've implemented. Thank you!

The arrows still appear when viewing a single record and are still broken:
`Missing argument 2 for JanVince\SmallRecords\Controllers\Records::update()`
`/var/www/html/plugins/janvince/smallrecords/controllers/Records.php line 126`

I noticed a small bug where if you delete a record from a list, it will show records from other lists in the list until you refresh the page.

There is also a bug with the custom order where it shows all records in all lists, instead of being able to create a custom order for each list.

I have a suggestion, as well. I think this plugin would be much more powerful if you could also create categories and tags for each individual list.

**Comment by omfgtora** [comment]
I would like to add a bit to the item deletion bug that shows all items from all lists. This only happens when you delete a record from the list view, not the item view.

**Comment by jan-vince** [comment]
Hi @omfgtora and thanks for issues.

I will try to fix them as soon as I will have some spare time!

Best regards,

Jan

**Comment by zlobec** [comment]
Hey @jan-vince 

Also a big fan of Small Records. I'm using it in almost every project now :D 

A bit of a request... When you'll be doing some update, could you connect the setting " Image width for Preview image column " with the image media preview and the images media, so it resizes the images to the setting's width and height.

Now if you add 10 images, each about 1.5mb in original size, it takes a bit long for each Record page in the backend to load. 

Thanks a bunch!
Regard,
Darjan

**Comment by jan-vince** [comment]
Hi @zlobec 

this is automatically done for ````record_image_preview```` column (it is a File object) but cannot be easily done for ````record_image_preview_media```` as it is only a path to the file.

I will keep it in my todo list!

**Comment by jan-vince** [comment]
Hi @omfgtora 

I have disabled prev/next buttons as they have never worked reliably. It was meant to speed up editing records, but it is not easy with multi-lists.

I have fixed custom ordering so only selected area records are shown.

I do not plan to add custom categories lists now, but will keep it in my todo list.

Thanks for issues!
