### ISSUE TITLE
Ability to sort records Inside Categories

### ISSUE THREAD

**Issue by artistro08** [jan-vince/smallrecords#91]
I would love to have the ability to sort records inside categories. For instance, If I go to a category, I would be able to bring up the custom order JUST for those records in that category and rearrange them. Would save a lot of time for people with portfolio pieces or any other type of lists.

**Comment by jan-vince** [comment]
Hi,

as far as I know sorting of relations must be defined on model level. So you have to extend my models or aou cn use other way. 

I do not know your use case but you can try:

* create a partial with Records component, where you define category property/slug and aou can call this partial with specific category as a parameter (so the partial will list records from given category only - and you can set sorting as you like)
* or if you use CategoryDetail component (like you have CMS page with category slug) you can add a Records component to accept same category slug and than you can list records from this component

best regards,

jan

**Comment by artistro08** [comment]
Thank you for this much appreciated.
